version: "3"

services:

  backend:
    build: ./Backend
    command: gunicorn main:app -w 2 --threads 2 -b 0.0.0.0:5000
    env_file:
      ./Backend/.env
    ports:
      - 5000:5000


  frontend:
    build: ./frontend
    command: npm run dev
    
    ports:
      - "3000:3000"